<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkImagenProducto</name>
   <tag></tag>
   <elementGuidId>d62fdc31-3196-473e-8ffa-7eac760f9dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>figure > picture.image-wrapper > img.image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@alt,' ${GlobalVariable.PRODUCTO}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//i.linio.com/p/cc50d6de951e2966cd71f42c19fc8519-catalog.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Monitor Samsung IPS de 22 Full HD Freesync 75Hz HDMI F22T350 - Negro</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catalogue-product-container&quot;)/div[@class=&quot;catalogue-product row&quot;]/a[1]/div[@class=&quot;image-container&quot;]/figure[1]/picture[@class=&quot;image-wrapper&quot;]/img[@class=&quot;image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catalogue-product-container']/div/a/div/figure/picture/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Monitor Samsung IPS de 22 Full HD Freesync 75Hz HDMI F22T350 - Negro']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/picture/img</value>
   </webElementXpaths>
</WebElementEntity>
